In [116]:
import numpy as np
## Qscore calculation
def rscore(GT, GX, sigmabeta2, sigmax2):
    nsnps = GT.shape[0]
    nsamples = GT.shape[1]
    ngenes = GX.shape[0]

    Yt = GX.T # shape N x G
    U, S, Vt = np.linalg.svd(Yt, full_matrices=False)
    S2 = np.square(S)
    S2mod = S2 + sigmax2 / sigmabeta2

    ## replace this with a vector array (pythonic version)
    Rscore = [None for i in range(nsnps)]
    for i in range(nsnps):
        Rscore[i] = np.sum(np.square(np.dot(U.T, GT[i,:])) * S2 / S2mod)
    Rscore = np.array(Rscore)

    return Rscore

import numpy as np
## Qscore calculation
def vectorised_rscore(GT, GX, sigmabeta2, sigmax2):
    nsnps = GT.shape[0]
    nsamples = GT.shape[1]
    ngenes = GX.shape[0]

    Yt = GX.T # shape N x G
    U, S, Vt = np.linalg.svd(Yt, full_matrices=False)
    S2 = np.square(S)
    S2mod = S2 + sigmax2 / sigmabeta2

    ## replace this with a vector array (pythonic version)
    Rscore = np.sum(np.square(np.dot(GT,U))*(S2/S2mod),axis = 1)
    return Rscore

In [117]:
GT = np.array([[0,1],[2,1],[0,0],[1,0]])

In [118]:
GT.shape

(4, 2)

In [119]:
GX = np.array([[0.5,0.9],[0.4,0.6],[0.2,0.2]])

In [120]:
GX

array([[0.5, 0.9],
       [0.4, 0.6],
       [0.2, 0.2]])

In [121]:
GX.shape

(3, 2)

In [122]:
rscore(GT,GX,0.016,1)

array([0.01886194, 0.09243938, 0.        , 0.00701659])

In [123]:
vectorised_rscore(GT,GX,0.016,1)

array([0.01886194, 0.09243938, 0.        , 0.00701659])

In [124]:
rscore(GT,GX,0.016,1).shape

(4,)

In [115]:
vectorised_rscore(GT,GX,0.016,1).shape

(4,)